
//  Words.swift
//  SightWords
//
//  Generated by Johan Jordaan on 31/7/2019.
//  Copyright © 2019 Johan Jordaan. All rights reserved.
//
let words = [
  SightWord(word: "the", rank: 1 ),
  SightWord(word: "and", rank: 2 ),
  SightWord(word: "i", rank: 3 ),
  SightWord(word: "to", rank: 4 ),
  SightWord(word: "a", rank: 5 )
]
